"""SQLAlchemy 2.0 async ORM models for MarketPulse India.

Conventions:
    * All primary keys are UUIDs generated by `uuid.uuid4`.
    * All timestamps are `TIMESTAMP WITH TIME ZONE` (TIMESTAMPTZ). Postgres
      normalizes to UTC; the API layer converts to IST for display.
    * `created_at` columns default at the database via `server_default=now()`.
    * Indexes are declared inline via `index=True` for single-column lookups.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import ClassVar

from sqlalchemy import (
    TIMESTAMP,
    Boolean,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import ARRAY, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

SEBI_DISCLAIMER_DEFAULT: str = "Not a SEBI registered advisor. For educational use only."


class Base(DeclarativeBase):
    """Declarative base shared by all ORM models."""

    type_annotation_map: ClassVar[dict[type, object]] = {}


# ---------------------------------------------------------------------------
# Reference data
# ---------------------------------------------------------------------------
class IndianStock(Base):
    __tablename__ = "indian_stocks"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    nse_symbol: Mapped[str] = mapped_column(String(20), unique=True, index=True, nullable=False)
    bse_code: Mapped[str | None] = mapped_column(String(10), nullable=True)
    company_name: Mapped[str] = mapped_column(String(100), nullable=False)
    sector: Mapped[str | None] = mapped_column(String(50), nullable=True)
    market_cap_cr: Mapped[float | None] = mapped_column(Float, nullable=True)
    is_nifty50: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="false", default=False
    )
    is_sensex30: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="false", default=False
    )
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )

    watchlist_entries: Mapped[list[WatchlistItem]] = relationship(
        back_populates="stock", cascade="all, delete-orphan"
    )


# ---------------------------------------------------------------------------
# Users + preferences
# ---------------------------------------------------------------------------
class User(Base):
    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    email: Mapped[str] = mapped_column(String(255), unique=True, nullable=False)
    phone_in: Mapped[str | None] = mapped_column(String(15), nullable=True)
    telegram_id: Mapped[str | None] = mapped_column(String(50), nullable=True)
    risk_profile: Mapped[str] = mapped_column(
        String(20), nullable=False, server_default="moderate", default="moderate"
    )
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )

    watchlist: Mapped[list[WatchlistItem]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )
    alert_preferences: Mapped[list[AlertPreference]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )


class WatchlistItem(Base):
    __tablename__ = "watchlist_items"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    nse_symbol: Mapped[str] = mapped_column(
        String(20),
        ForeignKey("indian_stocks.nse_symbol", ondelete="CASCADE"),
        nullable=False,
    )
    added_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )
    alert_threshold: Mapped[float] = mapped_column(
        Float, nullable=False, server_default="0.75", default=0.75
    )

    user: Mapped[User] = relationship(back_populates="watchlist")
    stock: Mapped[IndianStock] = relationship(back_populates="watchlist_entries")


class AlertPreference(Base):
    __tablename__ = "alert_preferences"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    min_confidence: Mapped[float] = mapped_column(
        Float, nullable=False, server_default="0.75", default=0.75
    )
    sectors: Mapped[list[str] | None] = mapped_column(ARRAY(Text), nullable=True)
    directions: Mapped[list[str]] = mapped_column(
        ARRAY(Text),
        nullable=False,
        server_default="{BUY}",
        default=lambda: ["BUY"],
    )
    channels: Mapped[list[str]] = mapped_column(
        ARRAY(Text),
        nullable=False,
        server_default="{email}",
        default=lambda: ["email"],
    )
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )

    user: Mapped[User] = relationship(back_populates="alert_preferences")


# ---------------------------------------------------------------------------
# Corporate announcements (raw + processed)
# ---------------------------------------------------------------------------
class Announcement(Base):
    __tablename__ = "announcements"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    nse_symbol: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    exchange: Mapped[str] = mapped_column(String(5), nullable=False)  # NSE | BSE
    announcement_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    raw_content: Mapped[str | None] = mapped_column(Text, nullable=True)
    s3_key: Mapped[str | None] = mapped_column(String(200), nullable=True)
    published_ist: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, index=True
    )
    processed: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="false", default=False
    )
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )


# ---------------------------------------------------------------------------
# Agent execution traces
# ---------------------------------------------------------------------------
class AnalysisSession(Base):
    __tablename__ = "analysis_sessions"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    thread_id: Mapped[str] = mapped_column(String(100), unique=True, nullable=False)
    nse_symbol: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    trigger_type: Mapped[str | None] = mapped_column(String(50), nullable=True)
    status: Mapped[str] = mapped_column(
        String(20), nullable=False, server_default="pending", default="pending"
    )
    started_at: Mapped[datetime | None] = mapped_column(TIMESTAMP(timezone=True), nullable=True)
    completed_at: Mapped[datetime | None] = mapped_column(TIMESTAMP(timezone=True), nullable=True)

    signals: Mapped[list[Signal]] = relationship(
        back_populates="session", cascade="all, delete-orphan"
    )
    retrieval_logs: Mapped[list[RetrievalLog]] = relationship(
        back_populates="session", cascade="all, delete-orphan"
    )


class Signal(Base):
    __tablename__ = "signals"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("analysis_sessions.id", ondelete="CASCADE"),
        nullable=False,
    )
    nse_symbol: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    direction: Mapped[str] = mapped_column(String(10), nullable=False)  # BUY|HOLD|SELL
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    current_price_inr: Mapped[float | None] = mapped_column(Float, nullable=True)
    target_price_inr: Mapped[float | None] = mapped_column(Float, nullable=True)
    upside_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    time_horizon_days: Mapped[int | None] = mapped_column(Integer, nullable=True)
    rationale: Mapped[str | None] = mapped_column(Text, nullable=True)
    sebi_disclaimer: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        server_default=SEBI_DISCLAIMER_DEFAULT,
        default=SEBI_DISCLAIMER_DEFAULT,
    )
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        index=True,
    )

    session: Mapped[AnalysisSession] = relationship(back_populates="signals")


class RetrievalLog(Base):
    __tablename__ = "retrieval_logs"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("analysis_sessions.id", ondelete="CASCADE"),
        nullable=False,
    )
    query: Mapped[str | None] = mapped_column(Text, nullable=True)
    docs_retrieved: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0", default=0
    )
    docs_graded_relevant: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default="0", default=0
    )
    used_web_fallback: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="false", default=False
    )
    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )

    session: Mapped[AnalysisSession] = relationship(back_populates="retrieval_logs")


__all__ = [
    "SEBI_DISCLAIMER_DEFAULT",
    "AlertPreference",
    "AnalysisSession",
    "Announcement",
    "Base",
    "IndianStock",
    "RetrievalLog",
    "Signal",
    "User",
    "WatchlistItem",
]
