"""Morning Digest Lambda — fires at 7 AM IST (1:30 AM UTC) via EventBridge.

Workflow
--------
1. Query Neon DB for the top-5 highest-confidence signals from the last 24 hrs.
2. Build an ``AlertPayload`` for each and fan out via the multi-channel dispatcher.
3. If zero signals exist, send a short "Good Morning / no signals" notice to
   the Telegram channel instead.
4. Return a summary dict with counts for CloudWatch / EventBridge inspection.

Environment variables
---------------------
DATABASE_URL            postgresql+asyncpg://... (async prefix is stripped here)
ENV                     dev | prod  — "dev" forces dry_run (default: dev)
ALERT_DRY_RUN           true | false — explicit override; takes precedence over ENV
WHATSAPP_ACCESS_TOKEN   }
WHATSAPP_PHONE_NUMBER_ID} see backend/alerts/dispatcher.py
WHATSAPP_TO_NUMBER      }
TELEGRAM_BOT_TOKEN      }
TELEGRAM_CHAT_ID        }
ALERT_SMS_NUMBER        }
LOG_LEVEL               INFO | DEBUG | WARNING  (default: INFO)

Local testing
-------------
    python -m lambdas.morning_digest.handler            # dry-run (safe default)
    python -m lambdas.morning_digest.handler --live     # real send (needs creds)
"""

from __future__ import annotations

import asyncio
import logging
import os
import sys
from datetime import datetime
from typing import Any
from zoneinfo import ZoneInfo

# ---------------------------------------------------------------------------
# Repo root on sys.path — lets the module be run directly from the repo root.
# In Lambda, backend/ is bundled into /var/task so this is a no-op.
# ---------------------------------------------------------------------------
_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.dirname(os.path.dirname(_HERE))
if _REPO_ROOT not in sys.path:
    sys.path.insert(0, _REPO_ROOT)

import psycopg  # noqa: E402 — psycopg3 sync API; bundled as psycopg[binary]
import telegram  # noqa: E402 — python-telegram-bot (for the no-signals notice)
from psycopg.rows import dict_row  # noqa: E402

from backend.alerts.dispatcher import AlertPayload, dispatch_alert  # noqa: E402

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

IST = ZoneInfo("Asia/Kolkata")

logger = logging.getLogger(__name__)
logger.setLevel(os.getenv("LOG_LEVEL", "INFO"))

_SIGNALS_QUERY = """
SELECT
    nse_symbol,
    direction,
    confidence,
    current_price_inr,
    target_price_inr,
    upside_pct,
    rationale,
    created_at
FROM signals
WHERE created_at > NOW() - INTERVAL '24 hours'
ORDER BY confidence DESC
LIMIT 5
"""

_NO_SIGNALS_TEXT = (
    "📊 MarketPulse India — Good Morning!\n"
    "No high-confidence signals in last 24hrs.\n"
    "Markets open at 9:15 AM IST."
)

_FALLBACK_POSITIVE = "High-confidence signal generated by MarketPulse analysis"
_FALLBACK_RISK = "Past performance does not guarantee future returns."

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _is_dry_run() -> bool:
    """Return True when no real alerts should be sent.

    Priority order:
    1. ``ALERT_DRY_RUN=true/false`` — explicit override
    2. ``ENV=dev`` — environment-level default (dev is always dry)
    """
    explicit = os.getenv("ALERT_DRY_RUN", "").strip().lower()
    if explicit in ("true", "1", "yes"):
        return True
    if explicit in ("false", "0", "no"):
        return False
    return os.getenv("ENV", "dev").lower() != "prod"


def _psycopg_url(db_url: str) -> str:
    """Strip the SQLAlchemy driver prefix so psycopg3 can parse the URL."""
    return (
        db_url.replace("postgresql+asyncpg://", "postgresql://")
        .replace("postgresql+psycopg2://", "postgresql://")
        .replace("postgresql+psycopg://", "postgresql://")
    )


def _quarter_label(dt: datetime) -> str:
    """Return the Indian fiscal-year quarter label for *dt*.

    Indian FY runs April–March; the label uses the year in which the FY ends.

    Examples (year 2026):
        May   2026 → Q1 FY27   (Apr–Jun 2026)
        Aug   2026 → Q2 FY27   (Jul–Sep 2026)
        Nov   2026 → Q3 FY27   (Oct–Dec 2026)
        Feb   2026 → Q4 FY26   (Jan–Mar 2026)
    """
    m, y = dt.month, dt.year
    if 4 <= m <= 6:
        return f"Q1 FY{(y + 1) % 100:02d}"
    if 7 <= m <= 9:
        return f"Q2 FY{(y + 1) % 100:02d}"
    if 10 <= m <= 12:
        return f"Q3 FY{(y + 1) % 100:02d}"
    return f"Q4 FY{y % 100:02d}"  # months 1–3


def _fetch_signals(db_url: str) -> list[dict[str, Any]]:
    """Return top-5 signals from the last 24 hours (synchronous).

    Uses psycopg3 with ``dict_row`` so every row is a plain dict.
    """
    conn_url = _psycopg_url(db_url)
    with psycopg.connect(conn_url, row_factory=dict_row) as conn:
        with conn.cursor() as cur:
            cur.execute(_SIGNALS_QUERY)
            return cur.fetchall()  # type: ignore[return-value]


def _row_to_payload(row: dict[str, Any]) -> AlertPayload:
    """Convert a ``signals`` table row to an ``AlertPayload``.

    Fields not stored in the ``signals`` table (revenue, PAT margin, company
    name) receive safe placeholder values so the dispatcher formatters never
    see missing data.  In a production setup these would come from a JOIN
    with an ``instruments`` / financial-data table.
    """
    created_at: datetime = row.get("created_at") or datetime.now(IST)
    if not isinstance(created_at, datetime):
        # psycopg3 returns timezone-aware datetimes, but guard just in case
        created_at = datetime.fromisoformat(str(created_at))

    # Truncate rationale to keep messages concise
    raw_rationale = str(row.get("rationale") or "").strip()
    key_positive = raw_rationale[:120] if raw_rationale else _FALLBACK_POSITIVE

    # DB columns are nullable — use safe non-zero defaults for gt=0 fields
    current = float(row.get("current_price_inr") or 0.0)
    target = float(row.get("target_price_inr") or 0.0)
    upside = float(row.get("upside_pct") or 0.0)

    direction = str(row.get("direction", "HOLD")).upper().strip()
    if direction not in ("BUY", "HOLD", "SELL"):
        direction = "HOLD"

    return AlertPayload(
        nse_symbol=str(row["nse_symbol"]),
        company_name=str(row["nse_symbol"]),   # no company name in signals table
        signal_direction=direction,
        confidence=float(row["confidence"]),
        current_price_inr=current if current > 0 else 1.0,
        target_price_inr=target if target > 0 else 1.0,
        upside_pct=upside,
        # revenue_cr / pat_margin_pct are not in the signals table;
        # use sentinel values so the AlertPayload validates without crashing.
        # The WhatsApp formatter shows "₹1 Cr revenue" — acceptable for digest.
        revenue_cr=1.0,
        pat_margin_pct=0.0,
        quarter=_quarter_label(created_at),
        key_positive=key_positive,
        key_risk=_FALLBACK_RISK,
        triggered_by="morning_digest",
    )


# ---------------------------------------------------------------------------
# Async layer
# ---------------------------------------------------------------------------


async def _send_no_signals_notice(dry_run: bool) -> None:
    """Send the no-signals Good Morning message to the Telegram channel.

    WhatsApp and SMS are skipped because this is a low-priority informational
    message (not a signal), and the WhatsApp Cloud API charges per message.
    """
    if dry_run:
        print(f"\n[morning_digest] No-signals notice preview:\n{_NO_SIGNALS_TEXT}\n")
        return

    tg_token = os.getenv("TELEGRAM_BOT_TOKEN", "")
    tg_chat = os.getenv("TELEGRAM_CHAT_ID", "")

    if not (tg_token and tg_chat):
        logger.info("[morning_digest] Telegram not configured — no-signals notice skipped")
        return

    bot = telegram.Bot(token=tg_token)
    try:
        await bot.send_message(chat_id=tg_chat, text=_NO_SIGNALS_TEXT)
        logger.info("[morning_digest] No-signals Good Morning notice sent to Telegram")
    except Exception as exc:  # noqa: BLE001
        logger.warning("[morning_digest] Telegram send failed for notice: %s", exc)


async def _dispatch_all(
    payloads: list[AlertPayload],
    dry_run: bool,
) -> tuple[int, list[str]]:
    """Fan out all payloads concurrently; return (alerts_sent, symbols_alerted)."""
    if not payloads:
        return 0, []

    results: list[dict[str, bool]] = list(
        await asyncio.gather(
            *[dispatch_alert(p, dry_run=dry_run) for p in payloads],
            return_exceptions=False,
        )
    )

    alerts_sent = 0
    symbols_alerted: list[str] = []

    for payload, result in zip(payloads, results):
        # Count as sent if at least one real channel succeeded
        channel_ok = any(v for k, v in result.items() if k != "dry_run")
        if channel_ok:
            alerts_sent += 1
            symbols_alerted.append(payload.nse_symbol)
            logger.info(
                "[morning_digest] ✓ %s | direction=%s confidence=%.0f%%",
                payload.nse_symbol,
                payload.signal_direction,
                payload.confidence * 100,
            )
        else:
            logger.warning(
                "[morning_digest] ✗ %s — no channel confirmed delivery", payload.nse_symbol
            )

    return alerts_sent, symbols_alerted


async def _run(rows: list[dict[str, Any]], dry_run: bool) -> dict[str, Any]:
    """Top-level coroutine — one event loop per Lambda invocation."""
    if not rows:
        await _send_no_signals_notice(dry_run)
        return {
            "status": "ok",
            "alerts_sent": 0,
            "symbols": [],
            "dry_run": dry_run,
            "note": "no_signals_in_24h",
        }

    payloads: list[AlertPayload] = []
    skipped: list[str] = []

    for row in rows:
        try:
            payloads.append(_row_to_payload(row))
        except Exception as exc:  # noqa: BLE001
            sym = str(row.get("nse_symbol", "?"))
            logger.warning("[morning_digest] payload build failed for %s: %s", sym, exc)
            skipped.append(sym)

    alerts_sent, symbols_alerted = await _dispatch_all(payloads, dry_run)
    return {
        "status": "ok",
        "alerts_sent": alerts_sent,
        "symbols": symbols_alerted,
        "skipped": skipped,
        "dry_run": dry_run,
    }


# ---------------------------------------------------------------------------
# Lambda entry point
# ---------------------------------------------------------------------------


def handler(event: dict[str, Any], context: object) -> dict[str, Any]:
    """Lambda entry point — called by EventBridge at 07:00 IST (01:30 UTC).

    Args:
        event:   EventBridge scheduled event dict (ignored).
        context: Lambda context object (ignored).

    Returns:
        Summary dict logged by CloudWatch and visible in EventBridge.
    """
    start = datetime.now(IST)
    dry_run = _is_dry_run()

    logger.info(
        "[morning_digest] started | ts=%s | dry_run=%s",
        start.strftime("%Y-%m-%d %H:%M:%S IST"),
        dry_run,
    )

    # ── 1. Validate env ──────────────────────────────────────────────────────
    db_url = os.getenv("DATABASE_URL", "")
    if not db_url:
        logger.error("[morning_digest] DATABASE_URL is not set")
        return {"status": "error", "detail": "DATABASE_URL not set", "alerts_sent": 0}

    # ── 2. Fetch signals (synchronous DB call) ───────────────────────────────
    try:
        rows = _fetch_signals(db_url)
        logger.info("[morning_digest] fetched %d signal(s) from last 24 hrs", len(rows))
    except Exception as exc:  # noqa: BLE001
        logger.exception("[morning_digest] DB fetch failed: %s", exc)
        return {"status": "error", "detail": str(exc), "alerts_sent": 0}

    # ── 3. Dispatch (async fan-out in one event loop) ────────────────────────
    result = asyncio.run(_run(rows, dry_run))

    # ── 4. Print execution summary ───────────────────────────────────────────
    elapsed_ms = int((datetime.now(IST) - start).total_seconds() * 1000)
    result["elapsed_ms"] = elapsed_ms

    print(
        f"[morning_digest] DONE | "
        f"signals_fetched={len(rows)} | "
        f"alerts_sent={result['alerts_sent']} | "
        f"symbols={result.get('symbols', [])} | "
        f"dry_run={dry_run} | "
        f"elapsed={elapsed_ms}ms"
    )
    return result


# ---------------------------------------------------------------------------
# Local testing
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse
    import json

    from dotenv import load_dotenv  # type: ignore[import-not-found]

    load_dotenv()

    parser = argparse.ArgumentParser(description="Morning Digest Lambda — local test runner")
    parser.add_argument(
        "--live",
        action="store_true",
        help="Actually send alerts (requires real credentials in .env). "
             "Without this flag, dry_run=True is forced regardless of .env.",
    )
    args = parser.parse_args()

    if not args.live:
        os.environ["ALERT_DRY_RUN"] = "true"
        print("[morning_digest] Running in DRY-RUN mode (pass --live to send for real)\n")
    else:
        print("[morning_digest] Running in LIVE mode — alerts will be sent!\n")

    result = handler({}, object())
    print(f"\n{'─' * 50}")
    print(json.dumps(result, indent=2, default=str))
